# 将 HLSL 源码嵌入为 C++ 头（原始字符串字面量），供运行时 D3DCompile 使用。
# 用法：
#   cmake -DSHADER_DIR=<dir> -DOUTPUT_HEADER=<file> "-DEMBED_ENTRIES=a.hlsl:VarA;b.hlsl:VarB" -P embed_shaders.cmake
#
# 每个条目生成 `inline constexpr char <Var>[] = R"shdr(...)shdr";`，
# 全部位于 PLUGIN_NAMESPACE 的 render_shaders 命名空间内。

set(RAW_STRING_DELIMITER "shdr")

set(HEADER "//\n// Generated by cmake/embed_shaders.cmake — do not edit.\n//\n\n#pragma once\n\n#include \"Plugin.h\"\n\nPLUGIN_NAMESPACE_BEGIN\n\nnamespace render_shaders\n{\n")

foreach(ENTRY IN LISTS EMBED_ENTRIES)
    string(REPLACE ":" ";" PAIR "${ENTRY}")
    list(LENGTH PAIR PAIR_LENGTH)
    if(NOT PAIR_LENGTH EQUAL 2)
        message(FATAL_ERROR "embed_shaders: malformed entry '${ENTRY}' (expected <file.hlsl>:<Variable>)")
    endif()
    list(GET PAIR 0 SHADER_FILE)
    list(GET PAIR 1 VARIABLE_NAME)

    file(READ "${SHADER_DIR}/${SHADER_FILE}" SHADER_CONTENT)

    string(FIND "${SHADER_CONTENT}" ")${RAW_STRING_DELIMITER}\"" DELIMITER_HIT)
    if(NOT DELIMITER_HIT EQUAL -1)
        message(FATAL_ERROR "embed_shaders: ${SHADER_FILE} contains the raw-string terminator )${RAW_STRING_DELIMITER}\"")
    endif()

    string(APPEND HEADER "\n// ${SHADER_FILE}\ninline constexpr char ${VARIABLE_NAME}[] = R\"${RAW_STRING_DELIMITER}(${SHADER_CONTENT})${RAW_STRING_DELIMITER}\";\n")
endforeach()

string(APPEND HEADER "\n} // namespace render_shaders\n\nPLUGIN_NAMESPACE_END\n")

file(WRITE "${OUTPUT_HEADER}" "${HEADER}")
message(STATUS "Embedded shader sources into ${OUTPUT_HEADER}")
